### ISSUE TITLE
[Bug] Themes no longer automatically reload after saving changes in the CSS file

### ISSUE THREAD

**Issue by KinoranaUPSB** [rauenzi/BetterDiscordApp#552]
Previously, when changes were saved in an active theme's CSS, BD would automatically reload the theme. With the recent stable update, that doesn't happen anymore. I'm unsure if a Discord update was what caused this to start happening, but I don't recall changing any settings. Manually reloading the theme or restarting discord still updates the theme.

Client settings:
Stable 75681 (2b1749b)
BBD 0.3.5
Host 0.0.261
Injector 0.6.2
OS X 10.15.6 (19.6.0)

**Comment by rauenzi** [comment]
This should have been fixed with this commit https://github.com/rauenzi/BetterDiscordApp/commit/01453d8792a7a9687e1c129449c836d7b21f0c5c

Can you try restarting your client?

**Comment by KinoranaUPSB** [comment]
> This should have been fixed with this commit [01453d8](https://github.com/rauenzi/BetterDiscordApp/commit/01453d8792a7a9687e1c129449c836d7b21f0c5c)
> 
> Can you try restarting your client?

Issue still persists after restarting and reinstalling BBD. Do you need any other info?

**Comment by rauenzi** [comment]
Check console for errors, and ensure the automatic loading setting is enabled.

**Comment by KinoranaUPSB** [comment]
> Check console for errors, and ensure the automatic loading setting is enabled.

Thank you, I had automatic loading disabled.
