### ISSUE TITLE
[Bug] BetterDiscord incompatible with latest Discord on Linux.

### ISSUE THREAD

**Issue by cow03haha** [rauenzi/BetterDiscordApp#598]
os: Debian 10 buster
discord: 0.0.14

when install betterdiscord at discord-0.0.14, it will not work and discord change to broswer version

![螢幕快照_2021-03-24_11-25-56](https://user-images.githubusercontent.com/44705326/112250167-e9787980-8c93-11eb-9189-a40c703635cc.png)

**Comment by Kotonoe** [comment]
Having the same problem. I tried to reinstall both BetterDiscord and Discord but nothing seems to be working.

**Comment by LimePotato** [comment]
Same bug here.

kernel 5.11.6-1-MANJARO

**Comment by itzjustas0** [comment]
same here.

Ubuntu 20.04.2 LTS

**Comment by HK0811** [comment]
same here
Ubuntu 20.04.1
Linux 64bit 5.8.0-45-Generic

**Comment by rauenzi** [comment]
This is known and is a duplicate of #442 / #548. In the future, reacting to the original issue with 👍 is more helpful to me to see who  is also experiencing these problems.

**Comment by 4n0nct** [comment]
Same thing here, but guys, I don't think mentionning your OS or your kernel is useful in this case, it's just discord which as always, at each updates, shit in the fan, nothing to do with your system.

So, is this bug critical or have you already an idea about how to fix it ?

**Comment by ylopp** [comment]
Same here, only happened when I updated to 0.0.14 on flatpak (fedora 33), tried reinstalling BetterDiscord and Discord, will not work.

**Comment by ObserverOfTime** [comment]
I adapted the patch from https://github.com/rauenzi/BetterDiscordApp/issues/442#issuecomment-805413148 for Linux. Here's how you can try it:

```bash
patch -Nu -d "$(betterdiscordctl status $flavor | sed -n 's/Modules: //p')" \
    -p0 --no-backup-if-mismatch < <(curl -Ss https://discord.coffee/hFDvPaj.patch)
```

Replace `$flavor` with:

* `-f ''` for stable
* `-f 'ptb'` for PTB
* `-f 'canary'` for Canary
* `--snap` for snap
* `--flatpak` for flatpak

It may or may not work for you.

**Comment by epicfacethe3rd** [comment]
this patch seems to not run at all.
```bash
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- discord_desktop_core/injector/betterdiscord/config.json
|+++ discord_desktop_core/injector/betterdiscord/config.json
````

**Comment by ObserverOfTime** [comment]
Adding `--follow-symlinks` to the patch command should fix the issue.

**Comment by epicfacethe3rd** [comment]
same issue still for me after adding ``--follow-symlinks``...

**Comment by ObserverOfTime** [comment]
Which flavor? What's the output of this command?

```sh
betterdiscordctl status $flavor | sed -n 's/Modules: //p'
```

**Comment by epicfacethe3rd** [comment]
> same issue still for me after adding `--follow-symlinks`...
> i should note this error was also present after manually dereferencing the symlink

there is no config.json file in my ``discord_desktop_core`` folder

> Which flavor? What's the output of this command (replacing `$flavor` as above)?
> 
> ```shell
> betterdiscordctl status $flavor | sed -n 's/Modules: //p'
> ```

I am on snap. output is ``/home/epicfacethe3rd/snap/discord/122/.config/discord/0.0.14/modules``

**Comment by ObserverOfTime** [comment]
Were you using BD beta before? The patch may not work on BD stable.

**Comment by epicfacethe3rd** [comment]
> Were you using BD beta before? The patch may not work on BD stable.

I don't honestly know. i'm going to guess no.

**Comment by epicfacethe3rd** [comment]
is there a way to get to bd beta?

**Comment by ObserverOfTime** [comment]
Not while BD is broken. :^)

**Comment by Rix565** [comment]
what time takes the patcher to patch ?

**Comment by Rix565** [comment]
10 minutes currently

**Comment by rauenzi** [comment]
> is there a way to get to bd beta?

Install normally and point the `config.json` to the beta branch. i.e. change `branch` value to `gh-pages-development`

**Comment by zany130** [comment]
> I adapted the patch from [#442 (comment)](https://github.com/rauenzi/BetterDiscordApp/issues/442#issuecomment-805413148) for Linux. Here's how you can try it:
> 
> ```shell
> patch -Nup0 -d "$(betterdiscordctl status $flavor | sed -n 's/Modules: //p')" \
>     --follow-symlinks --no-backup-if-mismatch < <(curl -Ss https://discord.coffee/hFDvPaj.patch)
> ```
> 
> Replace `$flavor` with:
> 
> * `-f ''` for stable
> * `-f 'ptb'` for PTB
> * `-f 'canary'` for Canary
> * `--snap` for Snap
> * `--flatpak` for Flatpak
> * `--nix` for Nixpkgs/NixOS
> 
> It may or may not work for you.

i got this 
```
patch -Nup0 -d "$(betterdiscordctl status -f '' | sed -n 's/Modules: //p')" \
    --follow-symlinks --no-backup-if-mismatch < <(curl -Ss https://discord.coffee/hFDvPaj.patch)
ERROR: Discord installation not found. Try specifying it with "--discord".
patch: **** Can't change to directory '' : No such file or directory
 ✘ zany130@fedora  ~  curl: (23) Failure writing output to destination
 ```

**Comment by etrigan63** [comment]
> > I adapted the patch from [#442 (comment)](https://github.com/rauenzi/BetterDiscordApp/issues/442#issuecomment-805413148) for Linux. Here's how you can try it:
> > ```shell
> > patch -Nup0 -d "$(betterdiscordctl status $flavor | sed -n 's/Modules: //p')" \
> >     --follow-symlinks --no-backup-if-mismatch < <(curl -Ss https://discord.coffee/hFDvPaj.patch)
> > ```
> > 
> > 
> > Replace `$flavor` with:
> > 
> > * `-f ''` for stable
> > * `-f 'ptb'` for PTB
> > * `-f 'canary'` for Canary
> > * `--snap` for Snap
> > * `--flatpak` for Flatpak
> > * `--nix` for Nixpkgs/NixOS
> > 
> > It may or may not work for you.
> 
> i got this
> 
> ```
> patch -Nup0 -d "$(betterdiscordctl status -f '' | sed -n 's/Modules: //p')" \
>     --follow-symlinks --no-backup-if-mismatch < <(curl -Ss https://discord.coffee/hFDvPaj.patch)
> ERROR: Discord installation not found. Try specifying it with "--discord".
> patch: **** Can't change to directory '' : No such file or directory
>  ✘ zany130@fedora  ~  curl: (23) Failure writing output to destination
> ```

Same here.

**Comment by zany130** [comment]
got it working on flatpak with 

```
patch -Nup0 -d "$(betterdiscordctl status --bd-repo-branch=gh-pages-development --flatpak | sed -n 's/Modules: //p')" \
    --follow-symlinks --no-backup-if-mismatch < <(curl -Ss https://discord.coffee/hFDvPaj.patch)
 ```

**Comment by Zarcix** [comment]
Try this instead(after you do `betterdiscordctl install`)

`curl "https://cdn.discordapp.com/attachments/409824216729255936/824346562737340436/Mod.patch" > Modified.patch; patch -Nup0 -d (betterdiscordctl status | sed -n 's/Linked injector directory: //p') --follow-symlinks < Modified.patch; rm -f Modified.patch`

I only tested this on stable discord so this may or may not work for those who use flatpak, snap, etc. (Can someone try?)

P.S I dunno how long that curl link's gonna last cause I dunno how long it takes for discord to remove files from their servers.

**Comment by ObserverOfTime** [comment]
> > I adapted the patch from [#442 (comment)](https://github.com/rauenzi/BetterDiscordApp/issues/442#issuecomment-805413148) for Linux. Here's how you can try it:
> > ```shell
> > patch -Nup0 -d "$(betterdiscordctl status $flavor | sed -n 's/Modules: //p')" \
> >     --follow-symlinks --no-backup-if-mismatch < <(curl -Ss https://discord.coffee/hFDvPaj.patch)
> > ```
> > 
> > 
> > Replace `$flavor` with:
> > 
> > * `-f ''` for stable
> > * `-f 'ptb'` for PTB
> > * `-f 'canary'` for Canary
> > * `--snap` for Snap
> > * `--flatpak` for Flatpak
> > * `--nix` for Nixpkgs/NixOS
> > 
> > It may or may not work for you.
> 
> i got this
> 
> ```
> patch -Nup0 -d "$(betterdiscordctl status -f '' | sed -n 's/Modules: //p')" \
>     --follow-symlinks --no-backup-if-mismatch < <(curl -Ss https://discord.coffee/hFDvPaj.patch)
> ERROR: Discord installation not found. Try specifying it with "--discord".
> patch: **** Can't change to directory '' : No such file or directory
>  ✘ zany130@fedora  ~  curl: (23) Failure writing output to destination
> ```

Are you sure you've installed stable Discord and not snap or flatpak?

**Comment by zany130** [comment]
> Try this instead(after you do `betterdiscordctl install`)
> 
> `curl "https://cdn.discordapp.com/attachments/409824216729255936/824346562737340436/Modified.patch" > Modified.patch; patch -Nup0 -d (betterdiscordctl status | sed -n 's/Linked injector directory: //p') --follow-symlinks < Modified.patch; rm -f Modified.patch`
> 
> I only tested this on stable discord so this may or may not work for those who use flatpak, snap, etc. (Can someone try?)
> 
> P.S I dunno how long that curl link's gonna last cause I dunno how long it takes for discord to remove files from their servers.
> 
> Edit: I accidentally put Mod.patch not Modified.patch
I got this
```
curl "https://cdn.discordapp.com/attachments/409824216729255936/824346562737340436/Modified.patch" > Modified.patch; patch -Nup0 -d (betterdiscordctl status | sed -n 's/Linked injector directory: //p') --follow-symlinks < Modified.patch; rm -f Modified.patch
bash: syntax error near unexpected token `('
```

**Comment by etrigan63** [comment]
I did the steps manually.
```
curl "https://cdn.discordapp.com/attachments/409824216729255936/824346562737340436/Mod.patch" > Modified.patch
patch -Nup0 -d "/home/<USERID>/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch
rm -f Modified.patch
```

**Comment by scaxyz** [comment]
> Try this instead(after you do `betterdiscordctl install`)
> 
> `curl "https://cdn.discordapp.com/attachments/409824216729255936/824346562737340436/Modified.patch" > Modified.patch; patch -Nup0 -d (betterdiscordctl status | sed -n 's/Linked injector directory: //p') --follow-symlinks < Modified.patch; rm -f Modified.patch`
> 
> I only tested this on stable discord so this may or may not work for those who use flatpak, snap, etc. (Can someone try?)
> 
> P.S I dunno how long that curl link's gonna last cause I dunno how long it takes for discord to remove files from their servers.
> 
> Edit: I accidentally put Mod.patch not Modified.patch

There is a missing `$`.
`... patch -Nup0 -d (betterdiscordctl ...` should be `... patch -Nup0 -d $(betterdiscordctl ...`.
After that it worked.

**Comment by Zarcix** [comment]
Switching discord link to mediafire cause it went inactive

New command:

curl "https://download1501.mediafire.com/bro8wwny39dg/rqpv9r67r5rpidq/Mod.patch" > Modified.patch; patch -Nup0 -d $(betterdiscordctl status | sed -n 's/Linked injector directory: //p') --follow-symlinks < Modified.patch; rm -f Modified.patch

**Comment by mik-at** [comment]
Workaround:

1. Restore from Backup to 0.0.13 (or don't update in the first place).
2. change "version" in /usr/share/discord/resources/build_info.json to "0.0.14".

Worked for me

**Comment by Vernoxvernax** [comment]
> Switching discord link to mediafire cause it went inactive
> 
> New command:
> 
> `curl "https://download1501.mediafire.com/bro8wwny39dg/rqpv9r67r5rpidq/Mod.patch" > Modified.patch; patch -Nup0 -d $(betterdiscordctl status | sed -n 's/Linked injector directory: //p') --follow-symlinks < Modified.patch; rm -f Modified.patch`

link ist out of date. just enter the url in the browser and copy the direct link for yourself.

**Comment by 4n0nct** [comment]
Bluffing build_info doesn't work for everybody
Your "patch" doesn't work for everytbody
I will wait for the real fix, from BD

**Comment by zany130** [comment]
working for me on stable by doing 
```betterdiscord --bd-repo-branch=gh-pages-development install ```
and then following Zaricix instructions although I had to download it from a browser curl wouldn't work.
![betterdiscord](https://user-images.githubusercontent.com/25832539/112374942-0ffcdb80-8cb9-11eb-8570-da8018c11b03.png)

**Comment by sniff122** [comment]
> I adapted the patch from [#442 (comment)](https://github.com/rauenzi/BetterDiscordApp/issues/442#issuecomment-805413148) for Linux. Here's how you can try it:
> 
> ```shell
> patch -Nup0 -d "$(betterdiscordctl status $flavor | sed -n 's/Modules: //p')" \
>     --follow-symlinks --no-backup-if-mismatch < <(curl -Ss https://discord.coffee/hFDvPaj.patch)
> ```
> 
> Replace `$flavor` with:
> 
>     * `-f ''` for stable
> 
>     * `-f 'ptb'` for PTB
> 
>     * `-f 'canary'` for Canary
> 
>     * `--snap` for Snap
> 
>     * `--flatpak` for Flatpak
> 
>     * `--nix` for Nixpkgs/NixOS
> 
> 
> It may or may not work for you.

this patch worked for me on discord stable on the stable version of BD

**Comment by cgarz** [comment]
Thanks to [ObserverOfTime's post](https://github.com/rauenzi/BetterDiscordApp/issues/598#issuecomment-805827642) I was able to fix things here on Arch.

However I had to fix the symlink issue in a more aggressive mannor. For some reason --follow-symlinks was not working for me.
My solution was to temporarily rename the injector link and move the folder that it points to into it's place. Then run the patch, then move the folder back and rename the injector link back to just injector again.

**Comment by WarpWing** [comment]
> I did the steps manually.
> 
> ```
> curl "https://cdn.discordapp.com/attachments/409824216729255936/824346562737340436/Mod.patch" > Modified.patch
> patch -Nup0 -d "/home/<USERID>/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch
> rm -f Modified.patch
> ```
> 
> Just edit for your user id.

THIS WORKS. LETS GO BABY

PS, You could do 
```bash
patch -Nup0 -d "/home/$USER/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch
```
instead no?

**Comment by etrigan63** [comment]
> > I did the steps manually.
> > ```
> > curl "https://cdn.discordapp.com/attachments/409824216729255936/824346562737340436/Mod.patch" > Modified.patch
> > patch -Nup0 -d "/home/<USERID>/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch
> > rm -f Modified.patch
> > ```
> > 
> > 
> > Just edit for your user id.
> 
> THIS WORKS. LETS GO BABY
> 
> PS, You could do
> 
> ```shell
> patch -Nup0 -d "/home/$USER/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch
> ```
> 
> instead no?

Probably. I was just being paranoid.

**Comment by orangemn6** [comment]
when I try any of these, debian, it says
```
patch -Nup0 -d "/home/$USER/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch            
patch unexpectedly ends in middle of line
patch: **** Only garbage was found in the patch input.

```

**Comment by WarpWing** [comment]
> when I try any of these, debian, it says
> 
> ```
> patch -Nup0 -d "/home/$USER/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch            
> patch unexpectedly ends in middle of line
> patch: **** Only garbage was found in the patch input.
> ```

Try it without the $USER and put your USER manuelly

**Comment by WarpWing** [comment]
I made a script that is curl-able so that you can execute the patch over CMDLine in one shot
```bash
/bin/bash -c "$(curl -fsSL https://gist.githubusercontent.com/WarpWing/631161668d32da957654938ba281c566/raw/5e2c41693922487265815518a5fe04fd8827fa1a/patch.sh)"
```
Please read the code to make sure that it's the code you want to run. I'm not responsible for anything that happens to your system

**Comment by Renkoto** [comment]
> when I try any of these, debian, it says
> 
> ```
> patch -Nup0 -d "/home/$USER/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch            
> patch unexpectedly ends in middle of line
> patch: **** Only garbage was found in the patch input.
> ```
*
Same, Manjaro.
Apparently curl link doesn't work.

**Comment by Renkoto** [comment]
> I made a script that is curl-able so that you can execute the patch over CMDLine in one shot.
> 
> NOTE: This should work for every flavor of BD. Please tell me if it doesn't and I'll update it accordingly. Also please read the [code](https://gist.github.com/WarpWing/631161668d32da957654938ba281c566) to make sure that it's the code you want to run. I'm not responsible for anything that happens to your system.
> 
> ```shell
> /bin/bash -c "$(curl -fsSL https://gist.githubusercontent.com/WarpWing/631161668d32da957654938ba281c566/raw/5e2c41693922487265815518a5fe04fd8827fa1a/patch.sh)"
> ```
> 
> Picture of it working
> ![image](https://user-images.githubusercontent.com/28925758/112399077-f1f4a280-8cdb-11eb-8fb0-be6e9db455c4.png)
> 
> Good luck fellow Linux Discordians and happy patching!
![imagen](https://user-images.githubusercontent.com/69415770/112404914-3d5c8000-8cdf-11eb-8539-9dfadbf27f42.png)

**Comment by epicfacethe3rd** [comment]
> I did the steps manually.
> 
> ```
> curl "https://cdn.discordapp.com/attachments/409824216729255936/824346562737340436/Mod.patch" > Modified.patch
> patch -Nup0 -d "/home/<USERID>/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch
> rm -f Modified.patch
> ```
> 
> Just edit for your user id.

this will not work for snap.
has anyone found a fix for snap based users on stable?

**Comment by Alec153** [comment]
The other links don't work so try this 

`curl "https://www.dropbox.com/s/tx8f3vzjaoascig/Mod.patch?dl=1" > Modified.patch; patch -Nup0 -d $(betterdiscordctl status | sed -n 's/Linked injector directory: //p') --follow-symlinks < Modified.patch; rm -f Modified.patch`

If that doesn't work try one of the other commands and replace the link with mine.

**Comment by guihkx** [comment]
I haven't tried the patch myself, but may I suggest you guys to host the patch on gist.github.com? It's more of a permanent solution, plus it has syntax highlighting. :D

**Comment by Renkoto** [comment]
> i seem to be getting the same error as you there. are you on the snap install?
AUR, stable.

**Comment by Alec153** [comment]
> > i seem to be getting the same error as you there. are you on the snap install?
> 
> AUR, stable.

Try mine. The error was because you weren't actually downloading anything as the links were broken.

**Comment by WarpWing** [comment]
> > I did the steps manually.
> > ```
> > curl "https://cdn.discordapp.com/attachments/409824216729255936/824346562737340436/Mod.patch" > Modified.patch
> > patch -Nup0 -d "/home/<USERID>/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch
> > rm -f Modified.patch
> > ```
> > 
> > 
> > Just edit for your user id.
> 
> this will not work for snap.
> has anyone found a fix for snap based users on stable?
> 
> > > I made a script that is curl-able so that you can execute the patch over CMDLine in one shot.
> > > NOTE: This should work for every flavor of BD. Please tell me if it doesn't and I'll update it accordingly. Also please read the [code](https://gist.github.com/WarpWing/631161668d32da957654938ba281c566) to make sure that it's the code you want to run. I'm not responsible for anything that happens to your system.
> > > ```shell
> > > /bin/bash -c "$(curl -fsSL https://gist.githubusercontent.com/WarpWing/631161668d32da957654938ba281c566/raw/5e2c41693922487265815518a5fe04fd8827fa1a/patch.sh)"
> > > ```
> > > 
> > > 
> > > Picture of it working
> > > ![image](https://user-images.githubusercontent.com/28925758/112399077-f1f4a280-8cdb-11eb-8fb0-be6e9db455c4.png)
> > > Good luck fellow Linux Discordians and happy patching!
> > > ![imagen](https://user-images.githubusercontent.com/69415770/112404914-3d5c8000-8cdf-11eb-8539-9dfadbf27f42.png)
> 
> i seem to be getting the same error as you there. are you on the snap install?

I was on the stable version. This patch script should work for all versions because it targets BetterDiscord regardless of the install path so it's a hmm moment.

**Comment by WarpWing** [comment]
```bash
curl "https://cdn.discordapp.com/attachments/409824216729255936/824346562737340436/Mod.patch" > Modified.patch
patch -Nup0 -d "/home/$USER/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch
rm -f Modified.patch
```
This is the current patch that worked for me. It's the code from the patch modified with $USER. For people that are new, run them individually because it could just be an issue with the script perhaps? Anyways good luck, still don't know why it wouldn't work for all versions. Also, note that the latest BD with patch breaks a few existing themes. My FrostedGlass Transparency is gone :(

**Comment by ObserverOfTime** [comment]
It won't work for snap and flatpak because they're not symlinked.

**Comment by WarpWing** [comment]
> It won't work for snap and flatpak because they're not symlinked.

Ah, let me see if I can make a non-symlink compatible version. Probably because it's under the snap/ and flatpak/ respectively.

**Comment by Barbarossa93** [comment]
@WarpWing Could you upload your patch to a github gist? Unfortunately your link returns this:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>
```

**Comment by WarpWing** [comment]
> @WarpWing Could you upload your patch to a github gist? Unfortunately your link returns this:
> 
> ```
> <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>
> ```

https://gist.github.com/WarpWing/631161668d32da957654938ba281c566
Here you go. Did the script not execute properly or?

**Comment by Barbarossa93** [comment]
Sorry, I should have been more clear. The first command `curl "https://cdn.discordapp.com/attachments/409824216729255936/824346562737340436/Mod.patch"` gives the xml output I mentioned above. I meant taking the contents from that curl link to a gist instead of that discord link that doesn't appear to work.

**Comment by HanabishiRecca** [comment]
You should use `$HOME` instead of `/home/$USER`, because user can change home directory location.

**Comment by 4n0nct** [comment]
Now that you have your own link can you stop spamming about your "patch" here or make a separate thread just about it?
The subject is about the incompatibility of latest linux discord version with bd, and all we can read is "muh my patch, my patch this my patch that". And also claiming on bd discord that it is THE FIX by linking this thread, seriously wtf.
We have seen it ok, thx, now stop.

**Comment by therealOri** [comment]
@WarpWing 
Running this:
patch -Nup0 -d "/home/ori/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch
or
patch -Nup0 -d "/$HOME/.local/share/betterdiscordctl/bd/0" --follow-symlinks < Modified.patch

Gives the following output in my terminal.
```
patch unexpectedly ends in middle of line
patch: **** Only garbage was found in the patch input.
```

Notes:
OS = Manjaro Linux
Using Stable

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Any other Ideas for a fix?

**Comment by Barbarossa93** [comment]
Nevermind @WarpWing, turns out @etrigan63's link is working again. Here's the [patch](https://gist.githubusercontent.com/Barbarossa93/f65e6e05fb685716920020a83960dfd2/raw/9a9c639305dde459a0f009b2148e6195d6982ece/gistfile1.txt) on github gists in case etrigan63's link goes down again.

@therealOri You're getting those errors because the "patch" from WarpWing's link is the xml output I mentioned [here](https://github.com/rauenzi/BetterDiscordApp/issues/598#issuecomment-806892507).

**Comment by therealOri** [comment]
@Barbarossa93 
What do I do with the patch that you have provided?

**Comment by Barbarossa93** [comment]
@therealOri See [here](https://github.com/rauenzi/BetterDiscordApp/issues/598#issuecomment-806067616).

**Comment by therealOri** [comment]
Alright, Worked like a charm!

**Comment by orangemn6** [comment]
@WarpWing 's solution worked perfectly for me

**Comment by huantianad** [comment]
I personally had to add a newline at the end of the patch for it to work properly

**Comment by MarkJeronimus** [comment]
The curl script didn't work for me, but I got it working.

Simply uninstalling and reinstalling with `betterdiscordctl uninstall && betterdiscordctl install` bd didn't work.

I had to delete the directory in order to get a clean file that the patch expect, by executing `sudo rm "/home/<USERID>/.local/share/betterdiscordctl"` in between.

These are the errors I got:

```
patching file betterdiscord/config.json
patching file betterdiscord/index.js
patching file betterdiscord/preload.js
patching file betterdiscord/remote.js
patching file index.js
patch unexpectedly ends in middle of line
patch: **** malformed patch at line 1284:  
```

When I tried after just uninstalling/reinstalling, the errors changed to:

```
patching file betterdiscord/config.json
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file betterdiscord/config.json.rej
patching file betterdiscord/index.js
Reversed (or previously applied) patch detected!  Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file betterdiscord/index.js.rej
patching file betterdiscord/preload.js
Hunk #3 FAILED at 9.
Hunk #4 FAILED at 13.
Hunk #5 FAILED at 22.
Hunk #6 FAILED at 31.
Hunk #7 FAILED at 36.
Hunk #8 FAILED at 46.
Hunk #9 FAILED at 55.
Hunk #11 FAILED at 68.
Hunk #12 FAILED at 74.
Hunk #13 FAILED at 76.
Hunk #14 FAILED at 79.
Hunk #15 FAILED at 81.
12 out of 15 hunks FAILED -- saving rejects to file betterdiscord/preload.js.rej
patching file betterdiscord/remote.js
patching file index.js
```

**Comment by jvyden** [comment]
The patch worked for me after trying the above solution (`rm -r $HOME/.local/betterdiscordctl`) but now on startup I'm getting a new error:
![image](https://user-images.githubusercontent.com/40577357/112543006-9a157480-8d8b-11eb-863c-e32fd5a33001.png)

And yes, I'm using the `discord_arch_electron` AUR package.

**Comment by WarpWing** [comment]
> The patch worked for me after trying the above solution (`rm -r $HOME/.local/betterdiscordctl`) but now on startup I'm getting a new error:
> ![image](https://user-images.githubusercontent.com/40577357/112543006-9a157480-8d8b-11eb-863c-e32fd5a33001.png)
> 
> And yes, I'm using the `discord_arch_electron` AUR package.

Try doing a clean reinstall of Discord. Perhaps manually update Electron.js?

**Comment by jvyden** [comment]
On Thu, 25 Mar 2021 14:04:10 -0700
Ty Chermsirivatana ***@***.***> wrote:
 

> Try doing a clean reinstall of Discord. Perhaps manually update Electron.js?

Might as well. The update to 0.0.14 wiped all my settings/gifs anyways lol.

By electron.js do you mean electron itself or something different?

**Comment by WarpWing** [comment]
> On Thu, 25 Mar 2021 14:04:10 -0700 Ty Chermsirivatana ***@***.***> wrote: Try doing a clean reinstall of Discord. Perhaps manually update Electron.js?
> Might as well. The update to 0.0.14 wiped all my settings/gifs anyways lol. By electron.js do you mean electron itself or something different?

Bleh my brain is on autopilot. I mean Electron itself yeah.

**Comment by jvyden** [comment]
Okay. I upgraded to `aur/electron-beta-bin` which uses electron `v13.0.0-beta.4` and modified my `/usr/bin/discord` to point to `electron-beta` but the same error persists.
For the record, I was using `community/electron` before, which is using electron v11.3.0.

**Comment by Slacksarenice** [comment]
curl "https://gist.githubusercontent.com/Slacksarenice/aaa09cffd8be9d06b62a49d780ba1e49/raw/9e9cc4795d31055adde141858d4dfe1232f0a224/betterdiscordfix.sh" | bash

one line script to fix issue

**Comment by ST3VI3-RICHI3** [comment]
> No worries. I upgraded to `aur/electron-beta-bin` which uses electron `v13.0.0-beta.4` and modified my `/usr/bin/discord` to point to `electron-beta` but the same error persists.
> For the record, I was using `community/electron` before, which is using electron v11.3.0.

I'm now at the same spot as you man. Any fix to this?

**Comment by jvyden** [comment]
> I'm now at the same spot as you man. Any fix to this?

Nope, unfortunately not. Glad to know it's not just me, though.

Are you using the official package or `aur/discord_arch_electron`?

**Comment by WarpWing** [comment]
> > I'm now at the same spot as you man. Any fix to this?
> 
> Nope, unfortunately not. Glad to know it's not just me, though.
> 
> Are you using the official package or `aur/discord_arch_electron`?
> 
> If the latter, which electron version?

Have you tried the clean install?

**Comment by r0nz-29** [comment]
> The curl script didn't work for me, but I got it working!
> 
> These were the errors I initially got:
> 
> ```
> patching file betterdiscord/config.json
> patching file betterdiscord/index.js
> patching file betterdiscord/preload.js
> patching file betterdiscord/remote.js
> patching file index.js
> patch unexpectedly ends in middle of line
> patch: **** malformed patch at line 1284:  
> ```
> 
> I re-downloaded the patch because it indicated it might be corrupt. After that, the errors changed to:
> 
> ```
> patching file betterdiscord/config.json
> Reversed (or previously applied) patch detected!  Skipping patch.
> 1 out of 1 hunk ignored -- saving rejects to file betterdiscord/config.json.rej
> patching file betterdiscord/index.js
> Reversed (or previously applied) patch detected!  Skipping patch.
> 3 out of 3 hunks ignored -- saving rejects to file betterdiscord/index.js.rej
> patching file betterdiscord/preload.js
> Hunk #3 FAILED at 9.
> Hunk #4 FAILED at 13.
> Hunk #5 FAILED at 22.
> Hunk #6 FAILED at 31.
> Hunk #7 FAILED at 36.
> Hunk #8 FAILED at 46.
> Hunk #9 FAILED at 55.
> Hunk #11 FAILED at 68.
> Hunk #12 FAILED at 74.
> Hunk #13 FAILED at 76.
> Hunk #14 FAILED at 79.
> Hunk #15 FAILED at 81.
> 12 out of 15 hunks FAILED -- saving rejects to file betterdiscord/preload.js.rej
> patching file betterdiscord/remote.js
> patching file index.js
> ```
> 
> I tried uninstalling/reinstalling bd, but the errors only increased, as if the file(s) to be patched didn't get reset at all.
> 
> I had to delete the bd directory in order to get a clean file that the patch expect, by executing `sudo rm "/home/<USERID>/.local/share/betterdiscordctl"` in between un/re-installing. After that, the patch worked.

Can you elaborate your workaround pls ?
I'm facing the same error, so I deleted that directory and then did `betterdiscordctl install` and then applied the patch, (which I downloaded from here: https://gist.githubusercontent.com/Barbarossa93/f65e6e05fb685716920020a83960dfd2/raw/9a9c639305dde459a0f009b2148e6195d6982ece/gistfile1.txt)
but it still gives me the same error....
(
OS: Arch
Discord stable
)

**Comment by jvyden** [comment]
> Have you tried the clean install?

Yes. I did so by wiping `~/.config/discord` but to no avail.

**Comment by ST3VI3-RICHI3** [comment]
> > I'm now at the same spot as you man. Any fix to this?
> 
> Nope, unfortunately not. Glad to know it's not just me, though.
> 
> Are you using the official package or `aur/discord_arch_electron`?
> 
> If the latter, which electron version?

I am using aur/discord_arch_electron. I'm using the stock electron version that comes with arch / that package.
Details in package manager GUI seen here: 
![image](https://user-images.githubusercontent.com/30847371/112644648-8d515900-8e3d-11eb-9819-aa562a7fafb9.png)

I have tried the vast majority of patches here all unsuccessful in their own ways.

Replying to @WarpWing:
> > > I'm now at the same spot as you man. Any fix to this?
> > 
> > Nope, unfortunately not. Glad to know it's not just me, though.
> > 
> > Are you using the official package or `aur/discord_arch_electron`?
> > 
> > If the latter, which electron version?
> Have you tried the clean install?

I have went between arch stable (now outdated), snap and flatpak, and I am now on AUR. A clean build was made when testing each patch, even uninstalling and re-downloading the package. Still no success.

**Comment by TheLastZombie** [comment]
Regarding https://github.com/rauenzi/BetterDiscordApp/issues/598#issuecomment-806070730: You can still get the old .deb and .tar.gz files from the following URLs:

- https://dl.discordapp.net/apps/linux/0.0.13/discord-0.0.13.deb
- https://dl.discordapp.net/apps/linux/0.0.13/discord-0.0.13.tar.gz

**Comment by ST3VI3-RICHI3** [comment]
For those still having this issue on an Arch based system (Manjaro in my case), I have a temporary fix:

1. install Discord 0.0.14 from official repos.
2. Next, run `sudo pacman -U /var/cache/pacman/pkg/discord-0.0.13-1-x86_64.pkg.tar.zst`. If you lack this file, you can download it [here](https://st3.zapto.org/files/discord-0.0.13-1-x86_64.pkg.tar.zst).
3. Install betterdiscord via `betterdiscordctl install`.*

*Should you get an error saying `ERROR: Directory 'discord_desktop_core' not found in /home/<Username>/.config/discord/0.0.14/modules`, wait for discord to install updates and fully launch and run again.

Credit to Jakub & Void for this fix.

**Comment by 4n0nct** [comment]
>     1. install Discord 0.0.13
>     3. build_info.json` and chance "version" to `0.0.14`
It has already been seed multiple times, on the discord server, and even here, that it doesn't work for everybody, making the app crash and rebooting endlessly after typing in the app.

**Comment by asorel1942** [comment]
> For those still having this issue on an Arch based system (Manjaro in my case), I have a temporary fix:
> 
> 1. install Discord 0.0.14 from official repos.
> 2. Next, run `sudo pacman -U /var/cache/pacman/pkg/discord-0.0.13-1-x86_64.pkg.tar.zst`. If you lack this file, you can download it [here](https://st3.zapto.org/files/discord-0.0.13-1-x86_64.pkg.tar.zst).
> 3. Once installed, run `sudo nano /opt/discord/resources/build_info.json` and chance "version" to `0.0.14`
> 4. Install betterdiscord via `betterdiscordctl install`.*
> 5. Run discord.
> 
> *Should you get an error saying `ERROR: Directory 'discord_desktop_core' not found in /home/<Username>/.config/discord/0.0.14/modules`, run discord and allow it to install updates and fully launch, then run betterdiscordctl again.
> 
> Credit to Jakub & Void for this fix.

For either this issue in particular or in general, is it "better" to get Discord from the official repositories on Manjaro, or the arch_electron version from the AUR?

**Comment by asorel1942** [comment]
I used one of the patches linked here, and had Betterdiscord working for a while. However, when I started Discord about an hour ago I got a message about Discord "rolling back" an update because of some kind of webhook incompatibility, after that I wasn't able to get it to work.

**Comment by TacoRaptor67** [comment]
> The curl script didn't work for me, but I got it working!
> 
> These were the errors I initially got:
> 
> ```
> patching file betterdiscord/config.json
> patching file betterdiscord/index.js
> patching file betterdiscord/preload.js
> patching file betterdiscord/remote.js
> patching file index.js
> patch unexpectedly ends in middle of line
> patch: **** malformed patch at line 1284:  
> ```
> 
> I re-downloaded the patch because it indicated it might be corrupt. After that, the errors changed to:
> 
> ```
> patching file betterdiscord/config.json
> Reversed (or previously applied) patch detected!  Skipping patch.
> 1 out of 1 hunk ignored -- saving rejects to file betterdiscord/config.json.rej
> patching file betterdiscord/index.js
> Reversed (or previously applied) patch detected!  Skipping patch.
> 3 out of 3 hunks ignored -- saving rejects to file betterdiscord/index.js.rej
> patching file betterdiscord/preload.js
> Hunk #3 FAILED at 9.
> Hunk #4 FAILED at 13.
> Hunk #5 FAILED at 22.
> Hunk #6 FAILED at 31.
> Hunk #7 FAILED at 36.
> Hunk #8 FAILED at 46.
> Hunk #9 FAILED at 55.
> Hunk #11 FAILED at 68.
> Hunk #12 FAILED at 74.
> Hunk #13 FAILED at 76.
> Hunk #14 FAILED at 79.
> Hunk #15 FAILED at 81.
> 12 out of 15 hunks FAILED -- saving rejects to file betterdiscord/preload.js.rej
> patching file betterdiscord/remote.js
> patching file index.js
> ```
> 
> I tried uninstalling/reinstalling bd, but the errors only increased, as if the file(s) to be patched didn't get reset at all.
> 
> I had to delete the bd directory in order to get a clean file that the patch expect, by executing `sudo rm "/home/<USERID>/.local/share/betterdiscordctl"` in between un/re-installing. After that, the patch worked.

I tried this, but still get the:
patch unexpectedly ends in middle of line
patch: **** malformed patch at line 1284:
Is there anything else that can be done? It seems to get so close to working... Tried looking at line 1284 myself, but as I figured, I don't understand at all what could be wrong.

**Comment by huantianad** [comment]
@TacoRaptor67 try adding a new line at the end of the patch, then uninstall and reinstall betterdiscord and re-do the patch. That fixed it for me

**Comment by TacoRaptor67** [comment]
> @TacoRaptor67 try adding a new line at the end of the patch, then uninstall and reinstall betterdiscord and re-do the patch. That fixed it for me

Welp.. that worked! Thanks :smile:

**Comment by Maritsu** [comment]
![image](https://user-images.githubusercontent.com/66056347/112791387-b81bf700-9061-11eb-8c8c-07c3d6bf4062.png)

Not working with 
```
$ patch -Nup0 -d "$(betterdiscordctl status | sed -n 's/Modules: //p')" \
    --follow-symlinks --no-backup-if-mismatch < <(curl -Ss https://discord.coffee/hFDvPaj.patch)
```

Discord 0.0.14 Stable, fresh install from `.deb` package.

**Comment by mkono87** [comment]
Linux Mint here, also not loading with Discord. Iv tried a few of the ideas from above but no luck.

**Comment by lamofgod** [comment]
Heads up: if you try to download and install 0.0.13 (at least on Ubuntu) Discord will force you to install 0.0.14

**Comment by Tropix126** [comment]
![image](https://user-images.githubusercontent.com/42101043/113211698-7050c780-923b-11eb-8e05-881423eb9202.png)
https://github.com/BetterDiscord/Installer/

**Comment by ObserverOfTime** [comment]
How do I make betterdiscordctl install this beta?
Should I just deprecate it in favour of the new installer?

**Comment by Tropix126** [comment]
> How do I make betterdiscordctl install this beta?
> Should I just deprecate it in favour of the new installer?

Unsure about how betterdiscordctl operates currently, but zere included a new install script in the main repo which allows you to manually inject using a similar method.

**Comment by rauenzi** [comment]
The inject script in the main repo currently goes to the wrong location. I can provide some detailed steps for betterdiscordctl hopefully tomorrow

**Comment by ObserverOfTime** [comment]
Maybe I'll adopt the [betterdiscord](https://aur.archlinux.org/packages/betterdiscord) AUR package (which currently installs the original, abandoned, and broken BD) to publish the new installer there. :thinking:

**Comment by rauenzi** [comment]
@ObserverOfTime thanks for doing that!

Would you prefer me to put some steps here on GitHub, or just DM them directly on Discord?

**Comment by ObserverOfTime** [comment]
Better here, I think, so other people can know them too.

**Comment by GideonWolfe** [comment]
Just to clarify, what are the steps to get up and running?

I just tried

* uninstall `betterdiscord-rauenzi-git`
* install `betterdiscord`
* `rm -r ~/.config/discord`
* `betterdiscordctl install`
* `discord`

And I am presented with the web app again. (system is arch linux)

**Comment by ObserverOfTime** [comment]
* `betterdiscord`

**Comment by GideonWolfe** [comment]
Wow, that's a slick installer, went off without a hitch. Much appreciated.
