### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by Voropoulo** [rauenzi/BetterDiscordApp#83]
Since yesterday night/today morning  (didn't check for 1-2 days so i'm not sure when it happened), even if i click at the tab "Themes" or "Plugins" or whatever, nothing comes up. It used to work.

**Comment by intrnl** [comment]
Duplicate of #80

**Comment by Kallyopae** [comment]
> Since yesterday night/today morning (didn't check for 1-2 days so i'm not sure when it happened), even if i click at the tab "Themes" or "Plugins" or whatever, nothing comes up. It used to work.

Reninstall BD. Latest discord updates broke some functionality of BD and by reinstalling it, they are fixed

**Comment by noxillio** [comment]
No, they are most certainly not fixed. I have reinstalled at least three times after this new BBD update and it's not working. I still get unresponsive BetterDiscord tabs in the settings.

![image](https://user-images.githubusercontent.com/40696585/47259626-e43af300-d479-11e8-92f3-0cbf864e3a88.png)

**Comment by Kallyopae** [comment]
On my side and others, these issues are fixed by reinstalling it

**Comment by noxillio** [comment]
And yet it isn't fixed for me. Others doesn't mean *all* others.

**Comment by Voropoulo** [comment]
I reinstalled discord app + BBD and it’s working

**Comment by Kallyopae** [comment]
> And yet it isn't fixed for me. Others doesn't mean _all_ others.

I know that and i haven't said ALL, just that this "fix" works for many others.

**Comment by noxillio** [comment]
> I reinstalled discord app + BBD and it’s working



> > And yet it isn't fixed for me. Others doesn't mean _all_ others.
> 
> I know that and i haven't said ALL, just that this "fix" works for many others.

Okay, so here's what I found.

When trying to reinstall to Canary, it doesn't work, even after reinstalling Canary altogether.
So, I tried installing to the Stable build, and it worked fine.

Looks like it's a Canary issue. Decided to just stick with Stable for now.

**Comment by rauenzi** [comment]
Fix for canary was just pushed, just need to reload/restart discord.

**Comment by SecuredArea** [comment]
Ok the theme tabs don't work for me.... doesn't show me the folder. help

**Comment by rauenzi** [comment]
Can you elaborate on that?

**Comment by Ashleyz4** [comment]
Plugins and Themes folders show nothing for me. Have reinstalled quite a few times, not fixed on latest release
[Image here](https://vgy.me/Pt8W2m.png)

**Comment by Ashleyz4** [comment]
aghhhhhh i feel stupid. some of them saved as .htm files even though i clearly right clicked the raw button on them. thanks github. my-bad.
